services:
  - type: web
    name: ecommerce-api
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
    rootDir: backend

  - type: web
    name: ecommerce-frontend
    runtime: docker
    dockerContext: frontend
    dockerfilePath: frontend/DockerfileA
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: ecommerce-api
          property: url
